from prompts.supervisor_prompt import get_supervisor_prompt
from prompts.sector_prompt import get_sector_analysis_prompt
from prompts.recommendation_prompt import build_recommendation_prompt
from prompts.conversation_prompt import build_conversation_system_prompt